// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: internal/grpc/proto/node.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_internal_grpc_proto_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_node_proto_rawDescGZIP(), []int{0}
}

type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       uint64                 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	GenesisHash   string                 `protobuf:"bytes,2,opt,name=genesis_hash,json=genesisHash,proto3" json:"genesis_hash,omitempty"`
	NodeVersion   string                 `protobuf:"bytes,3,opt,name=node_version,json=nodeVersion,proto3" json:"node_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_internal_grpc_proto_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_node_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeRequest) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *HandshakeRequest) GetGenesisHash() string {
	if x != nil {
		return x.GenesisHash
	}
	return ""
}

func (x *HandshakeRequest) GetNodeVersion() string {
	if x != nil {
		return x.NodeVersion
	}
	return ""
}

type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_internal_grpc_proto_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_node_proto_rawDescGZIP(), []int{2}
}

func (x *HandshakeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HandshakeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NodeStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	LastHash      string                 `protobuf:"bytes,2,opt,name=last_hash,json=lastHash,proto3" json:"last_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_internal_grpc_proto_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_node_proto_rawDescGZIP(), []int{3}
}

func (x *NodeStatus) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *NodeStatus) GetLastHash() string {
	if x != nil {
		return x.LastHash
	}
	return ""
}

type BlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockRequest) Reset() {
	*x = BlockRequest{}
	mi := &file_internal_grpc_proto_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRequest) ProtoMessage() {}

func (x *BlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRequest.ProtoReflect.Descriptor instead.
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_node_proto_rawDescGZIP(), []int{4}
}

func (x *BlockRequest) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type BlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockResponse) Reset() {
	*x = BlockResponse{}
	mi := &file_internal_grpc_proto_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockResponse) ProtoMessage() {}

func (x *BlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockResponse.ProtoReflect.Descriptor instead.
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_node_proto_rawDescGZIP(), []int{5}
}

func (x *BlockResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *BlockResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_internal_grpc_proto_node_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_node_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/grpc/proto/node.proto\x12\x0fquantumpay.grpc\"\a\n" +
	"\x05Empty\"s\n" +
	"\x10HandshakeRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x04R\achainId\x12!\n" +
	"\fgenesis_hash\x18\x02 \x01(\tR\vgenesisHash\x12!\n" +
	"\fnode_version\x18\x03 \x01(\tR\vnodeVersion\"G\n" +
	"\x11HandshakeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"A\n" +
	"\n" +
	"NodeStatus\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x1b\n" +
	"\tlast_hash\x18\x02 \x01(\tR\blastHash\"&\n" +
	"\fBlockRequest\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\"9\n" +
	"\rBlockResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data2\xf6\x01\n" +
	"\vNodeService\x12R\n" +
	"\tHandshake\x12!.quantumpay.grpc.HandshakeRequest\x1a\".quantumpay.grpc.HandshakeResponse\x12@\n" +
	"\tGetStatus\x12\x16.quantumpay.grpc.Empty\x1a\x1b.quantumpay.grpc.NodeStatus\x12Q\n" +
	"\x10GetBlockByHeight\x12\x1d.quantumpay.grpc.BlockRequest\x1a\x1e.quantumpay.grpc.BlockResponseB:Z8github.com/irlan/quantumpay-go/internal/grpc/proto;protob\x06proto3"

var (
	file_internal_grpc_proto_node_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_node_proto_rawDescData []byte
)

func file_internal_grpc_proto_node_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_node_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_node_proto_rawDesc), len(file_internal_grpc_proto_node_proto_rawDesc)))
	})
	return file_internal_grpc_proto_node_proto_rawDescData
}

var file_internal_grpc_proto_node_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_grpc_proto_node_proto_goTypes = []any{
	(*Empty)(nil),             // 0: quantumpay.grpc.Empty
	(*HandshakeRequest)(nil),  // 1: quantumpay.grpc.HandshakeRequest
	(*HandshakeResponse)(nil), // 2: quantumpay.grpc.HandshakeResponse
	(*NodeStatus)(nil),        // 3: quantumpay.grpc.NodeStatus
	(*BlockRequest)(nil),      // 4: quantumpay.grpc.BlockRequest
	(*BlockResponse)(nil),     // 5: quantumpay.grpc.BlockResponse
}
var file_internal_grpc_proto_node_proto_depIdxs = []int32{
	1, // 0: quantumpay.grpc.NodeService.Handshake:input_type -> quantumpay.grpc.HandshakeRequest
	0, // 1: quantumpay.grpc.NodeService.GetStatus:input_type -> quantumpay.grpc.Empty
	4, // 2: quantumpay.grpc.NodeService.GetBlockByHeight:input_type -> quantumpay.grpc.BlockRequest
	2, // 3: quantumpay.grpc.NodeService.Handshake:output_type -> quantumpay.grpc.HandshakeResponse
	3, // 4: quantumpay.grpc.NodeService.GetStatus:output_type -> quantumpay.grpc.NodeStatus
	5, // 5: quantumpay.grpc.NodeService.GetBlockByHeight:output_type -> quantumpay.grpc.BlockResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_node_proto_init() }
func file_internal_grpc_proto_node_proto_init() {
	if File_internal_grpc_proto_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_node_proto_rawDesc), len(file_internal_grpc_proto_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_node_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_node_proto_depIdxs,
		MessageInfos:      file_internal_grpc_proto_node_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_node_proto = out.File
	file_internal_grpc_proto_node_proto_goTypes = nil
	file_internal_grpc_proto_node_proto_depIdxs = nil
}
