// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: internal/grpc/proto/service.proto

package proto

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChainHeight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainHeight) Reset() {
	*x = ChainHeight{}
	mi := &file_internal_grpc_proto_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainHeight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainHeight) ProtoMessage() {}

func (x *ChainHeight) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainHeight.ProtoReflect.Descriptor instead.
func (*ChainHeight) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *ChainHeight) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Value         uint64                 `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	Nonce         uint64                 `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_internal_grpc_proto_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TransactionRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TransactionRequest) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TransactionRequest) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *TransactionRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_internal_grpc_proto_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransactionResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

var File_internal_grpc_proto_service_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_service_proto_rawDesc = "" +
	"\n" +
	"!internal/grpc/proto/service.proto\x12\x04node\x1a\x1bgoogle/protobuf/empty.proto\"%\n" +
	"\vChainHeight\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\"\x82\x01\n" +
	"\x12TransactionRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x04R\x05value\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\x04R\x05nonce\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\"C\n" +
	"\x13TransactionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash2\x88\x01\n" +
	"\x04Node\x126\n" +
	"\tGetHeight\x12\x16.google.protobuf.Empty\x1a\x11.node.ChainHeight\x12H\n" +
	"\x11SubmitTransaction\x12\x18.node.TransactionRequest\x1a\x19.node.TransactionResponseB\x17Z\x15./internal/grpc/protob\x06proto3"

var (
	file_internal_grpc_proto_service_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_service_proto_rawDescData []byte
)

func file_internal_grpc_proto_service_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_service_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_service_proto_rawDesc), len(file_internal_grpc_proto_service_proto_rawDesc)))
	})
	return file_internal_grpc_proto_service_proto_rawDescData
}

var file_internal_grpc_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_grpc_proto_service_proto_goTypes = []any{
	(*ChainHeight)(nil),         // 0: node.ChainHeight
	(*TransactionRequest)(nil),  // 1: node.TransactionRequest
	(*TransactionResponse)(nil), // 2: node.TransactionResponse
	(*empty.Empty)(nil),         // 3: google.protobuf.Empty
}
var file_internal_grpc_proto_service_proto_depIdxs = []int32{
	3, // 0: node.Node.GetHeight:input_type -> google.protobuf.Empty
	1, // 1: node.Node.SubmitTransaction:input_type -> node.TransactionRequest
	0, // 2: node.Node.GetHeight:output_type -> node.ChainHeight
	2, // 3: node.Node.SubmitTransaction:output_type -> node.TransactionResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_service_proto_init() }
func file_internal_grpc_proto_service_proto_init() {
	if File_internal_grpc_proto_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_service_proto_rawDesc), len(file_internal_grpc_proto_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_service_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_service_proto_depIdxs,
		MessageInfos:      file_internal_grpc_proto_service_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_service_proto = out.File
	file_internal_grpc_proto_service_proto_goTypes = nil
	file_internal_grpc_proto_service_proto_depIdxs = nil
}
